seed: 1235

dataset:
  train:
    tfrecords: 'data/tf_example/training'
    idxs: 'data/idxs_training_bs_1'
  valid:
    tfrecords: 'data/tf_example/validation'
    idxs: 'data/idxs_validation_bs_1'
  batchsize: 1

# dataset:
#   train:
#     tfrecords: 'data/tfrecords'
#     idxs: 'data/idxs'
#   valid:
#     tfrecords: 'data/tfrecords'
#     idxs: 'data/idxs'
#   batchsize: 2

model:
  in_feature_dim: 9  # 9!
  feature_dim: 256  # 256!
  time_steps: 91  # 91!
  in_dynamic_rg_dim: 3  # 3!
  in_static_rg_dim: 6  # 6!
  head_num: 1  # 4~1
  k: 1  # 4~1
  F: 6  # 6!

device_ids: '0'
device_num: 0
max_epochs: 10


